# Configuration
# https://jekyllrb.com/docs/configuration/

theme: minima
repository: FriendsOfOxid/community-map
plugins: []
timezone: Europe/Berlin

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: Oxid Community Map
description: A map filled with people being involved in Oxid esales. Hosted on GitHub, which allows everyone to add their map entries. Join!

# Assets
# https://jekyllrb.com/docs/assets/
sass:
    style: compressed

# Collections
# https://jekyllrb.com/docs/collections/
collections:
- directory

# Exclude directories and/or files from the conversion.
# https://jekyllrb.com/docs/configuration/
exclude:
- CONTRIBUTE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SETUP.md
- vendor

# Compress HTML in Jekyll
# http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
